### ISSUE TITLE
What are you using macupd for?

### ISSUE THREAD

**Issue by skarfacegc** [bthaase/DDWarden#6]
I haven't really been able to figure much out about what it's supposed to do.  (I haven't dug much, and the macupd.c source doesn't say a whole log)

**Comment by bthaase** [comment]
Netflow provides traffic by IP address, but since most people use automatic DHCP in their homes, it makes it difficult to track devices accurately over a period of time, because they might grab a different IP address.

Macupd routinely sends a list of IP addresses and their associated mac addresses for each device. Warden uses that to store device data by mac address, so even if they grab a new IP address the data is grouped correctly.
